"""criar tabela tarefa

Revision ID: 36ba336e0c60
Revises: 
Create Date: 2026-08-17 08:01:18.686752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '36ba336e0c60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('materia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prazo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('concluida', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefa')
    # ### end Alembic commands ###
